### ISSUE TITLE
Python code for the widget in this repo.

### ISSUE THREAD

**Issue by prmpsmart** [laserpants/qt-material-widgets#44]
I took the task to transcode the cpp source codes of the widgets in this repository into python for the Qt bindings PySide6, PyQt5 and PySide2.

the repo is [prmpsmart/qt-material-widgets](https://github.com/prmpsmart/qt-material-widgets)

**Comment by Detector-I** [comment]
> I took the task to transcode the cpp source codes of the widgets in this repository into python for the Qt bindings PySide6, PyQt5 and PySide2.
> 
> the repo is [prmpsmart/qt-material-widgets](https://github.com/prmpsmart/qt-material-widgets)

good, but why its empty then??

**Comment by prmpsmart** [comment]
I'll commit the scripts later this month, I had to work on another supposed group project alone, because it's urgent.

**Comment by prmpsmart** [comment]
The python version has been commited to https://github.com/prmpsmart/qt-material-widgets

**Comment by YouKnow-sys** [comment]
nice, thank you

**Comment by issam-seghir** [comment]
> The python version has been commited to https://github.com/prmpsmart/qt-material-widgets

Has the project been abandoned ?

**Comment by prmpsmart** [comment]
No, it hasn't be abandoned, it'll be updated once completed.
Contributors are welcomed, just lemme know if anyone wanna be added to the project
